# Licence and copyright of the files that cannot carry a header (JSON, Markdown, ...): see https://reuse.software
version = 1

[[annotations]]
path = ["**/*.json", "**/*.md", "**/*.xml", "**/*.jpg", "**/*.png", "**/*.yml", "REUSE.toml", ".gitignore", "pytest.ini"]
SPDX-FileCopyrightText = "2026 shaysudm"
SPDX-License-Identifier = "AGPL-3.0-or-later"
